query getGarments {
  garments {
    nodes {
      garmentFields {
        excludeOnHomepage
        construction
        description
        linkToTiktok
        name
        patternDescription
        provenance
        rights
        version
        publicDomain
        patternZipDownload {
          node {
            altText
            mediaItemUrl
          }
        }
        patternPngPreview {
          node {
            altText
            mediaItemUrl
          }
        }
        threeDFileGlb {
          node {
            altText
            mediaItemUrl
          }
        }
      }
      slug
    }
  }
}