query getGlobalSettings {
  globalSettingsPage {
    globalSettings {
      about
      contact
      passwordConfig
      legalAndRightsContent
      publicDomainTextContent
      passwordEntryInfo
      homepageBackgroundImage {
        node {
            altText
            mediaItemUrl
          }
      }
      homepageBackgroundImageText
      homepageBackgroundImagePositioning
      homepageBackgroundImagePositioningMobile
      homepageBackgroundImageTheme
    }
  }
}